on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: reusable
        name: Reusable action
        uses: ./.github/actions/hello
        with:
          who-to-greet: "Stan Wozniak"
      - run: echo random-number ${{ steps.reusable.outputs.random-number }}
        shell: bash
